cart/urls.py
from django.conf.urls import url
from django.urls import  path
from . import views

app_name = 'cart'

urlpatterns = [
    path('yourcart', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import  path
from . import views

app_name = 'orders'

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('payment-success/',views.payment_success,name='payment_success'),
    path('payment-fail/',views.payment_fail,name='payment_fail'),

    path("orders/",views.orders,name="orders"),
    path('order_items/<str:order_number>/<int:pk>/',views.order_items,name='order_items'),

]

solvergeek/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import  handler404,handler500
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('ecommerce/',include('ecommerce.urls')),
    path('',include('ecommerce.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('',include('orders.urls')),
    path('',include('cart.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns+=static(settings.MEDIA_ROOT,document_root=settings.MEDIA_ROOT)

handler404 = 'ecommerce.views.error404'
handler500 = 'ecommerce.views.error500'

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 101)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from ecommerce.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from  django.http import  HttpResponse

@require_POST
def cart_add(request,product_id):
    cart = Cart(request)  # create a new cart object passing it the request object 
    product = get_object_or_404(Product, id=product_id) 
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    
    # return HttpResponse()
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request,'cart/cart_detail.html', {'cart': cart})

templates/cart/cart_detail.html
{% extends 'header1.html' %}

{% load static %}
{% load humanize %}
{% load thumbnail %}
{% block title %}

Your Shopping Cart
{% endblock %}


{% block content %}

<!-- start -->
<div class="container">
<div class="row">
    <div class="col">
        <div class="order-summary clearfix">
           
                <h3 class="title">Cart Review</h3>
            
            <table class="shopping-cart-table table">
                <thead>
                    <tr>
                        <th>Item</th>
                        <th class="text-center">Price</th>
                        <th class="text-center">Quantity</th>
                        <th class="">Remove</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in cart %}
                    {% with product=item.product  %}
                    <tr>
                        <td class="thumb">
                            <a href="{{product.get_absolute_url}}">
                                
                                <img src="{{ product.image|thumbnail_url:'avatar' }}" alt="" style="width:fit-content;height:fit-content;">
                            </a>
                            <a href="{{product.get_absolute_url}}">{{product.name}}</a>

                        </td>

                        
                        <td class="price text-center"><strong>GH₵ {{product.price|intcomma}}</strong><br><del
                                class="font-weak"><small>$40.00</small></del></td>

                        <td class="qty text-center">
                            <form action="{% url "cart:cart_add" product.id %}" method="post">
                                {% csrf_token %}
                                <p> {{ item.update_quantity_form.quantity }}</p>
                                <p> {{ item.update_quantity_form.update }}</p>
                                <br>
                                <input type="submit" value="Update" class="btn">
                            </form>
                        </td>
                        <td class="">
                            <a class="main-btn icon-btn fa fa-close" href="{% url "cart:cart_remove" product.id %}">❌</a>
                    </td>
                    </tr>

                    {% endwith %}
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <th class="empty" colspan="3"></th>
                        <th>SUBTOTAL</th>
                        <th colspan="2" class="sub-total">GH₵ {{ cart.get_total_price|intcomma }}</th>
                    </tr>
                    <tr>
                        <th class="empty" colspan="3"></th>
                        <th>SHIPING</th>
                        <td colspan="2">Free Shipping</td>
                    </tr>
                    <tr>
                        <th class="empty" colspan="3"></th>
                        <th>TOTAL</th>
                        <th colspan="2" class="total">
                            {% with totail_items=cart|length %}
                            {% if cart|length > 0 %}
                            GH₵ {{ cart.get_total_price|intcomma }}
                            {% else %}
                            Your cart is empty.
                            {% endif %}
                            {% endwith %}
                        </th>
                    </tr>
                </tfoot>
            </table>
           
        </div>
        <ul>
            <li>
                <a class="btn primary-btn my-4" href="/">Continue Shopping</a>
                {% if cart.get_total_price > 1 %}
                <a style="background-color: #4654A3;" href="{% url "orders:checkout" %}" class="btn btn-primary">Checkout</a>
    
                {% endif %}
            </li>
        </ul>
    </div>
    
</div>
</div>

<style>
    table{
        text-align: center;
    }
</style>

{% endblock %}