cart/urls.py
from django.conf.urls import url
from django.urls import  path
from . import views

app_name = 'cart'

urlpatterns = [
    path('yourcart', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import  path
from . import views

app_name = 'orders'

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('payment-success/',views.payment_success,name='payment_success'),
    path('payment-fail/',views.payment_fail,name='payment_fail'),

    path("orders/",views.orders,name="orders"),
    path('order_items/<str:order_number>/<int:pk>/',views.order_items,name='order_items'),

]

solvergeek/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import  handler404,handler500
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('ecommerce/',include('ecommerce.urls')),
    path('',include('ecommerce.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('',include('orders.urls')),
    path('',include('cart.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns+=static(settings.MEDIA_ROOT,document_root=settings.MEDIA_ROOT)

handler404 = 'ecommerce.views.error404'
handler500 = 'ecommerce.views.error500'

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 101)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

templates/add_product.html
{% extends 'header1.html' %}

{% load crispy_forms_tags %}

{% load static %}

{% block content %}

<script src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>



<div class="container">
    


<main class="main my-4">
    <h2 class="text-center">
        <b style="font-weight: bolder; font-size: larger;">
            EKOL XTAYCONNECT AFRICA LIMITED
            Online Store/Website
        </b>
    </h2>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <strong>{{message}}</strong> 
            </div>
            
            <script>
              $(".alert").alert();
            </script>
        {% endfor %}
    {% endif %}
    <div class="row justify-content-center">
        <div class="col-md-6">
                <h3 class="text-center font-weight-bold">ADD AN ITEM TO {{product|upper}}</h3>

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    {{form|crispy}}
                       <ul style="text-align: center;">
                           <li >
                            <button type="submit" class="btn btn-info">Submit</button>
            
                            <a class="btn btn-info" href="{% url 'create_form' %}">Back</a>
                           </li>
                       </ul>
                </form>
        </div>
    </div>
    
       

</main><!-- End .main -->

</div>



{% endblock %}

templates/base.html
{% extends 'header1.html' %}

{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
   
<!--  -->

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

<!--  -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
  <div class="container">
    <div class="row justify-content-center">
      {% block body %}

      {% if messages %}
      <div>
        <strong class="message">Messages:</strong>
        <ul>
    {% for message in messages %}
    <li class="message">{{message}}</li>
    {% endfor %}
        </ul>
      </div>
      {% endif %}
  
      <div>
  
        </ul>
      </div>
      {% block content %}
      {% endblock %}
      {% endblock %}
      {% block extra_body %}
      {% endblock %}
    </div>
  </div>
  <script>
  
  $('.message').fadeOut(5000).css('color','red')
  </script>

  </body>
</html>

templates/categories.html
{% extends 'header1.html' %}
{% load thumbnail %}

{% load static %}

{% block content %}
<main class="main">
   


   
   
        <div class="container">
           
            <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item">
                    <a style="color: #CE7D0E;" class="nav-link active" id="featured-products-tab" data-toggle="tab" href="#featured-products"
                        role="tab" aria-controls="featured-products" aria-selected="true"> {{allrelated.name}}  </a>
                </li>
                
              
            </ul>
         
        </div><!-- End .container -->
        <main class="main">
   
     
           
            <div class="container">
                <div class="row">
                {% for product in products %}
                <div class="col-md-3">
                                         
                    <div class="product-default">
                        <figure>
                           
                            <a href="{{product.get_absolute_url}}">
                                <img src="{{product.image.url}}">`
                            </a>
                        </figure>
                        <div class="product-details">
                            <div class="ratings-container">
                                <div class="product-ratings">
                                    <span class="ratings" style="width:400"></span><!-- End .ratings -->
                                </div><!-- End .product-ratings -->
                            </div><!-- End .product-container -->
                          
                            <h2 class="product-title">
                                <a id="product-name" href="{{product.get_absolute_url}}">{{product.name}}</a>
                                <h6 id="product-id">{{product.id}}</h6>
                            </h2>
                            <div class="price-box">
                                <span class="product-price">GH₵ {{product.price}}</span>
                            </div><!-- End .price-box -->
                            <div class="product-action">
                                <a href="#" class="btn-icon-wish"><i class="icon-heart"></i></a>
                                <button class="btn-icon btn-add-cart" style="background-color: #4654A3;color: white;" data-toggle="modal"
                                    data-target="#addCartModal"><i class="icon-bag"></i>ADD TO CART</button>
                                <a href="{{product.get_absolute_url}}" class="btn-quickview" title="Quick View"><i
                                        class="fas fa-external-link-alt"></i></a>
                            </div>
                        </div><!-- End .product-details -->
                    </div>
                 
                  
             
                  
            </div>
                {% endfor %}
                </div>
            </div><!-- End .container -->
        
     





<div class="mb-1"></div><!-- margin -->

<div class="promo-section" style="background-image: url('{% static "images/promo-bg.jpg" %}')">
    <div class="container">
        <h3>the perfect gift</h3>
        <h4>Check off your list with our best gifts</h4>
        <!-- <a href="#" class="btn btn-primary">Shop Now</a> -->
    </div><!-- End .container -->
</div><!-- End .promo-section -->

<div class="partners-container">
    <div class="container">
        <div class="partners-carousel owl-carousel owl-theme">
            <a href="#" class="partner">
                <img src="{% static 'images/logos/1.png' %}" alt="logo">
            </a>
            <a href="#" class="partner">
                <img src="{% static 'images/logos/2.png' %}" alt="logo">
            </a>
            <a href="#" class="partner">
                <img src="{% static 'images/logos/3.png' %}" alt="logo">
            </a>
            <a href="#" class="partner">
                <img src="{% static 'images/logos/4.png' %}" alt="logo">
            </a>
            <a href="#" class="partner">
                <img src="{% static 'images/logos/5.png' %}" alt="logo">
            </a>
            <a href="#" class="partner">
                <img src="{% static 'images/logos/2.png' %}" alt="logo">
            </a>
            <a href="#" class="partner">
                <img src="{% static 'images/logos/1.png' %}" alt="logo">
            </a>
        </div><!-- End .partners-carousel -->
    </div><!-- End .container -->
</div><!-- End .partners-container -->

{% if resent_view_products %}
    

<div class="container">
    <h3 class="h4 title">Recently viewed items</h3>
    <div class="row">
     
        
        {% for  resent_view_products in resent_view_products %}
        
            
        <div class="col-6 col-lg-3">
            <div class="product-column">
               

                <div class="product-default left-details product-widget mb-3">
                    <figure>
                        <a href="{{resent_view_products.get_absolute_url}}">
                            <img src="{{resent_view_products.image.url}}">
                        </a>
                    </figure>
                    <div class="product-details">
                        <h2 class="product-title">
                            <a href="{{resent_view_products.get_absolute_url}}">{{resent_view_products.name}}</a>
                        </h2>
                        <div class="ratings-container">
                            <div class="product-ratings">
                                <span class="ratings" style="width:100%"></span><!-- End .ratings -->
                                <span class="tooltiptext tooltip-top"></span>
                            </div><!-- End .product-ratings -->
                        </div><!-- End .product-container -->
                        <div class="price-box">
                            <span class="product-price">GH₵ {{resent_view_products.price}}</span>
                        </div><!-- End .price-box -->
                    </div><!-- End .product-details -->
                </div>
                
               
            </div><!-- End .product-column -->
        </div><!-- End .col-lg-3 -->
        {% endfor %}
    </div>
       
</div>
{% endif %}


<div class="mb-6"></div><!-- margin -->
</main><!-- End .main -->

<style>
#product-id{
    display: none;
    visibility: hidden;
}
</style>
{% endblock %}

templates/category_form.html
{% extends 'header1.html' %}

{% load crispy_forms_tags %}

{% load static %}

{% block content %}


<div class="container">
    


<main class="main my-4">
    <h2 class="text-center">
        <b style="font-weight: bolder; font-size: larger;">
            EKOL XTAYCONNECT AFRICA LIMITED
            Online Store/Website
        </b>
    </h2>
    <div class="form-group float-right">
        <h4>ADD A NEW CATEGORY</h4>
        <form method="post">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="btn btn-primary pulse" style="background-color:#7B5685">Save</button>
        </form>
    </div>

    <div class="container">


        <div class="row justify-content-center">
            {% for object in categories %}

            <div class="col-md-6">

                <ul class="list-unstyled font-weight-bold">
                    <li>Category: {{object.name}} </li>
                </ul>

                <table class="table">

                    <thead>
                        <tr>
                            
                            <th>SUBCATEGORY</th>
                            <th>Add New</th>
                        </tr>
                    </thead>
                    <td>
                        <form action="{% url 'create_subcategory' object.id %}" method="post">
                            {% csrf_token %}
                           <div class="form-group">
                            <!-- <input type="text" name="name" placeholder="enter name" id=""> -->
                            {{form|crispy}}
                            <script>
                                document.getElementById('id_name').placeholder='add new'
                            </script>
                            <button type="submit" class="btn btn-primary" style="background-color: rgb(76, 90, 168);">Submit</button>
                           </div>
                        </form>
                  </td>

                    {% for  subcategiry in object.sub_categories.all %}



                    <tbody>
                        <tr>
                            <td> {{subcategiry.name}} </td>
                            <td> 
                                <a href="{% url 'add_product' subcategiry.id  %}">add</a>
                            </td>
                                
                        </tr>
                    
                        {% endfor %}
                    </tbody>
                    
                </table>
            </div>
            {% endfor %}
        </div>
    </div>

</main><!-- End .main -->

</div>



{% endblock %}

templates/product_detail.html
{% extends 'header1.html' %}
{% load static %}
{% block content %}

{% load humanize %}

<script src="{% static 'js/jquery.min.js' %}"></script>
 

	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				<!--  Product Details -->
				
					<div class="col-md-6">
						<div id="product-main-view">
							<div class="product-view">
								{% if product.image.url %}
								<img src="{{product.image.url}}" alt="">

								{% endif %}
							</div>
							<div class="product-view">
								{% if product.image1.url %}
								<img src="{{product.image1.url}}" alt="">

								{% endif %}
							</div>
							<div class="product-view">
								{% if product.image2.url %}
								<img src="{{product.image2.url}}" alt="">

								{% endif %}
							</div>
							<div class="product-view">
								{% if product.image3.url %}
								<img src="{{product.image3.url}}" alt="">

								{% endif %}
							</div>
						</div>
						<div id="product-view">
							<div class="product-view">
								{% if product.image1.url %}
								<img src="{{product.image.url}}" alt="">

								{% endif %}
							</div>
							<div class="product-view">
								{% if product.image1.url %}
								<img src="{{product.image1.url}}" alt="">

								{% endif %}
							</div>
							<div class="product-view">
								{% if product.image2.url %}
								<img src="{{product.image2.url}}" alt="">

								{% endif %}
							</div>
							<div class="product-view">
								{% if product.image3.url %}
								<img src="{{product.image3.url}}" alt="">

								{% endif %}
							</div>
						</div>
                    </div>
                   
					<div class="col-md-6">
						<div class="product-body">
							<div class="product-label">
								<span>New</span>
								<span class="sale">-20%</span>
							</div>
							<h2 id="product" class="product-name">{{product.name}}</h2>
							<h3 class="product-price">GH¢ {{product.price|intcomma}}<del class="product-old-price "> GH¢ 45.00</del></h3>
							
							<p><strong>Availability:</strong> {{available|yesno:"No,Yes" }}</p>
							<!-- <p><strong>Brand:</strong> E-SHOP</p> -->
							
						
							<form id="cart-form" method="POST">
									
								<div class="form-group product-btns">
									<div class="qty-input">
										<span class="text-uppercase">QTY: </span>
                                        <input class="input quantity" type="number" id="quantity" required>
                                        <button id="addtocart" class="primary-btn add-to-cart my-4 mb-4"><i class="fa fa-shopping-cart"></i> Add to Cart</button> <br>
                                            <b class="btn mb-4 text-light btn-block" style="background-color: #CE7D0E;" id="saved-message"></b>
                                    </div>  
                                    
                                    <p>{{product.description|safe}}</p>
								 <h3><a id="checkout" href="{% url 'orders:checkout' %}"></a></h3>
                                </div>
								</form>
								</div>
								<ul id="modelId" style="justify-content: center;">
									<li>
										<button  style="background-color: #4654A3;color: white;" class="main-btn"><a class="text-light" href="{% url 'orders:checkout' %}">CONTINEU SHOPPING<i class="fa fa-arrow-circle-right"></i> </a></button>
									<button  style="background-color: #4654A3;color: white;" class="main-btn"><a class="text-light" href="{% url 'cart:cart_detail' %}">VIEW CART &  CHECKOUT <i class="fa fa-shopping-cart"></i> </a></button>
								
									</li>
								</ul>
								
								
				
						
						</div>
					
			

				</div>
				<!-- /Product Details -->
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->

	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				<!-- section title -->
				<div class="col-md-12">
					<div class="section-title">
						<h2 class="title">Picked For You</h2>
					</div>
				</div>
				<!-- section title -->

				{% for popular in popular|slice:'0:8' %}
				  
				
				<!-- Product Single -->
				<div class="col-md-3 col-sm-6 col-xs-6">
					<div class="product product-single">
						<a href="{{popular.get_absolute_url}}">
						<div class="product-thumb">
							<div class="product-label">
								<span style="background-color: #4654A3" class="sale text-light">-20%</span>
							</div>
							<button class="main-btn quick-view"><i class="fa fa-search-plus"></i> Quick view</button>
							<img src="{{popular.image.url}}" alt="">
						</div>
						<div class="product-body">
							<h3  class="product-price"> GH¢ {{popular.price}} <del class="product-old-price">$45.00</del></h3>
							<div class="product-rating">
								<!-- <i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star-o empty"></i> -->
							</div>
							<h2 class="product-name">{{popular.name}}</h2>
						</a>
							<div class="product-btns">
								<a  style="background-color: #4654A3;color: white;" class="primary-btn btn-block  add-to-cart text-center" href="{{products.get_absolute_url}}">View Details</a>

								<!-- <button class="main-btn icon-btn"><i class="fa fa-heart"></i></button>
								<button class="main-btn icon-btn"><i class="fa fa-exchange"></i></button>
								<button class="primary-btn add-to-cart"><i class="fa fa-shopping-cart"></i> Add to Cart</button>
								 -->
							</div>
						</div>
					</div>
				</div>
				<!-- /Product Single -->
				{% endfor %}
				
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->



<style>
    #id_quantity{
        height: 35px;
        width: 80px;
	}
	#id_quantity:hover{
		width: 100px;

	}

	.main-btn{
		margin-top: 1em;
	
	
	}
	
</style>



<script>
$('#modelId,#saved-message').fadeOut('fast')

	// add to cart

	$('#cart-form').on('submit',function(e){
		
		e.preventDefault();
       
        product_id = '{{product.id}}'

     
      url ='/add/'+product_id+'/'
	
		$.ajax({
			type:'POST',
			url:url,
		
			data:{
			 
                product:product_id,
				quantity:$('#quantity').val(),
				// update_quantity:$('#update_quantity').val(),
			 
				csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
		
			},
		beforeSend:function(){
            $('#saved-message').text('adding to cart...')
		

		},
		
			success:function(){
				// location.reload()
				// $('#checkout').fadeIn().text('checkout')
                old_quantity = "{{cart|length}}"
                // alert(old_quantity)
				new_quantity = $('.quantity').val()
                new_value= parseInt(old_quantity)+parseInt(new_quantity)
                console.log('old_quantity', old_quantity,)
                $('.cart-count').text(new_value)
                

                $('#quantity').val('')

                $('#saved-message').text('added to cart...')
                $('#modelId,#saved-message').fadeIn('fast')
                $('#saved-message').fadeOut(4002)
				console.log('saved')

			},
			error:function(){
			alert('error')
			}
	
		})
	})
	
		</script>
    
    

{% endblock %}

templates/search.html
{% extends 'header1.html' %}
{% load thumbnail %}

{% load static %}

{% block content %}
<main class="main">
   
     
           
                <div class="container">
                    <div class="row">
                    {% for product in products %}
                    <div class="col-md-3">
                                             
                        <div class="product-default">
                            <figure>
                               
                                <a href="{{product.get_absolute_url}}">
                                    <img src="{{product.image.url}}">`
                                </a>
                            </figure>
                            <div class="product-details">
                                <div class="ratings-container">
                                    <div class="product-ratings">
                                        <span class="ratings" style="width:400"></span><!-- End .ratings -->
                                    </div><!-- End .product-ratings -->
                                </div><!-- End .product-container -->
                              
                                <h2 class="product-title">
                                    <a id="product-name" href="{{product.get_absolute_url}}">{{product.name}}</a>
                                    <h6 id="product-id">{{product.id}}</h6>
                                </h2>
                                <div class="price-box">
                                    <span class="product-price">GH₵ {{product.price}}</span>
                                </div><!-- End .price-box -->
                                <div class="product-action">
                                    <a href="#" class="btn-icon-wish"><i class="icon-heart"></i></a>
                                    <button  style="background-color: #4654A3;color: white;" class="btn-icon btn-add-cart" data-toggle="modal"
                                        data-target="#addCartModal"><i class="icon-bag"></i>ADD TO CART</button>
                                    <a href="{{product.get_absolute_url}}" class="btn-quickview" title="Quick View"><i
                                            class="fas fa-external-link-alt"></i></a>
                                </div>
                            </div><!-- End .product-details -->
                        </div>
                     
                      
                 
                      
                </div>
                    {% endfor %}
                    </div>
                </div><!-- End .container -->
            
         
    
  
   
    

    <div class="mb-1"></div><!-- margin -->

    <div class="promo-section" style="background-image: url('{% static "images/promo-bg.jpg" %}')">
        <div class="container">
            <h3>the perfect gift</h3>
            <h4>Check off your list with our best gifts</h4>
            <a href="#" class="btn btn-primary">Shop Now</a>
        </div><!-- End .container -->
    </div><!-- End .promo-section -->

    <div class="partners-container">
        <div class="container">
            <div class="partners-carousel owl-carousel owl-theme">
                <a href="#" class="partner">
                    <img src="{% static 'images/logos/1.png' %}" alt="logo">
                </a>
                <a href="#" class="partner">
                    <img src="{% static 'images/logos/2.png' %}" alt="logo">
                </a>
                <a href="#" class="partner">
                    <img src="{% static 'images/logos/3.png' %}" alt="logo">
                </a>
                <a href="#" class="partner">
                    <img src="{% static 'images/logos/4.png' %}" alt="logo">
                </a>
                <a href="#" class="partner">
                    <img src="{% static 'images/logos/5.png' %}" alt="logo">
                </a>
                <a href="#" class="partner">
                    <img src="{% static 'images/logos/2.png' %}" alt="logo">
                </a>
                <a href="#" class="partner">
                    <img src="{% static 'images/logos/1.png' %}" alt="logo">
                </a>
            </div><!-- End .partners-carousel -->
        </div><!-- End .container -->
    </div><!-- End .partners-container -->

	<!-- section -->
	<div class="section">
		<!-- container -->
		<div class="container">
			<!-- row -->
			<div class="row">
				<!-- section title -->
				<div class="col-md-12">
					<div class="section-title">
						<h2 class="title">Picked For You</h2>
					</div>
				</div>
				<!-- section title -->

				{% for popular in popular|slice:'0:8' %}
				  
				
				<!-- Product Single -->
				<div class="col-md-3 col-sm-6 col-xs-6">
					<div class="product product-single">
						<a href="{{popular.get_absolute_url}}">
						<div class="product-thumb">
							<div class="product-label">
								<span style="background-color: #4654A3" class="sale text-light">-20%</span>
							</div>
							<button class="main-btn quick-view"><i class="fa fa-search-plus"></i> Quick view</button>
							<img src="{{popular.image.url}}" alt="">
						</div>
						<div class="product-body">
							<h3  class="product-price"> GH¢ {{popular.price}} <del class="product-old-price">$45.00</del></h3>
							<div class="product-rating">
								<!-- <i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star"></i>
								<i class="fa fa-star-o empty"></i> -->
							</div>
							<h2 class="product-name">{{popular.name}}</h2>
						</a>
							<div class="product-btns">
								<a  style="background-color: #4654A3;color: white;" class="primary-btn btn-block  add-to-cart text-center" href="{{products.get_absolute_url}}">View Details</a>

								<!-- <button class="main-btn icon-btn"><i class="fa fa-heart"></i></button>
								<button class="main-btn icon-btn"><i class="fa fa-exchange"></i></button>
								<button class="primary-btn add-to-cart"><i class="fa fa-shopping-cart"></i> Add to Cart</button>
								 -->
							</div>
						</div>
					</div>
				</div>
				<!-- /Product Single -->
				{% endfor %}
				
			</div>
			<!-- /row -->
		</div>
		<!-- /container -->
	</div>
	<!-- /section -->


    <div class="mb-6"></div><!-- margin -->
</main><!-- End .main -->

<style>
    #product-id{
        display: none;
        visibility: hidden;
    }
</style>
{% endblock %}