cart/urls.py
from django.conf.urls import url
from django.urls import  path
from . import views

app_name = 'cart'

urlpatterns = [
    path('yourcart', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import  path
from . import views

app_name = 'orders'

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('payment-success/',views.payment_success,name='payment_success'),
    path('payment-fail/',views.payment_fail,name='payment_fail'),

    path("orders/",views.orders,name="orders"),
    path('order_items/<str:order_number>/<int:pk>/',views.order_items,name='order_items'),

]

solvergeek/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import  handler404,handler500
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('ecommerce/',include('ecommerce.urls')),
    path('',include('ecommerce.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('',include('orders.urls')),
    path('',include('cart.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns+=static(settings.MEDIA_ROOT,document_root=settings.MEDIA_ROOT)

handler404 = 'ecommerce.views.error404'
handler500 = 'ecommerce.views.error500'

orders/models.py
from django.db import models
from django.core.validators import RegexValidator
from ecommerce.models import Product
import datetime
from ecommerce.models import Base_Model




def increment_order_number():
  last_order = Order.objects.all().order_by('id').last()
  if not last_order:
    return '' + str(datetime.date.today().year) + str(datetime.date.today().month).zfill(2) + '0000'
  order_number = last_order.order_number
  order_int = int(order_number[9:13])
  new_order_int = order_int + 1
  new_order_id = '' + str(str(datetime.date.today().year)) + str(datetime.date.today().month).zfill(2) + str(new_order_int).zfill(4)
  return new_order_id

class Order(Base_Model):
    name = models.CharField(max_length=60)
    email = models.EmailField()
    address = models.CharField(max_length=150)
    # phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+233'. Up to 15 digits allowed.")
    phone_number = models.CharField(max_length=15, blank=False)
    city = models.CharField('City/Closest Landmark',max_length=100)
    # created = models.DateTimeField(auto_now_add=True)
    # updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    order_number = models.CharField('order number',max_length=500,editable=False,default=increment_order_number)

    class Meta:
        ordering = ('-date_updated', )

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
    
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(Base_Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.order.name)

    def get_cost(self):
        if self.price and self.quantity:

            return self.price * self.quantity
        else:
            return None


    def grand_total(self):
        print(sum(self.get_cost))
        return sum(self.get_cost)

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['name', 'email', 'address', 'phone_number', 'city',]

orders/views.py
from django.shortcuts import render,redirect,get_object_or_404

from django.conf import settings
# from uniqstore.settings import EMAIL_HOST_USER
from  django.contrib import  messages
from django.core.mail import send_mail
from django.core.mail import send_mass_mail
from .models import OrderItem,Order
from .forms import OrderCreateForm
from cart.cart import Cart
from django.db.models import Q



def checkout(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            order_number = order.order_number
           
           
            # 
            # subject = 'order placed'
            # message = ' A customer just sent a request to purchase a product get to admin for more info '
            # email_from = settings.EMAIL_HOST_USER
            # recipient_list = ['aggrey.en@live.com',]
            # send_mail( subject, message, email_from, recipient_list,fail_silently=False )

           
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item['product'],
                    price=item['price'],
                    quantity=item['quantity'],
                )

               
                # for key, value in request.POST.items():
                    # pass
                   
                alldate = form.cleaned_data
                name = form.cleaned_data.get('name')
                customer_email = form.cleaned_data.get('email')
                address = form.cleaned_data.get('address')
                phone_number = form.cleaned_data.get('phone_number')
                city = form.cleaned_data.get('city')
                
                # subject = 'order placed'
                # message = ' A customer just sent a request to purchase a product get to admin for more info '
                # recepient = [customer_email]
                # # email_from = settings.EMAIL_HOST_USER
                # send_mail(subject, 
                # message, EMAIL_HOST_USER, ['aggrey.en@live.com'], fail_silently = False)
            
                # print(first_name,email,address,phone_number,city)
                
                #send  mass email
                # email_from = settings.EMAIL_HOST_USER
                # message1 = ('Hello aggrey ', f'a customer with phone { phone_number } and name { name } from {city} having { order_number } as order number had ordered for a product sign in to admin for more info use the phone,email,name order number to search', email_from, ['aggrey.en@live.com','aggrey.en@gmail.com',])
                # message2 = ('Hello ' f'{ name } your order number is {order_number}','\n\tOrder placed successfully we will call u soon please keep the order number safe. Thanks for shopping with us', email_from, [customer_email])
                # try:
                #     send_mass_mail((message1, message2), fail_silently=False)

                # except:
                #     messages.info(request,f'email not sent but your order was placed successfully your order number is\t<h4><b><u>{order_number}</u></b></h4>\tkindly feel free to give us a call on\
                #     <b>0240699506</b> please keep the order number safe')
                #     cart.clear()
                #     return redirect('orders:checkout')

          
            cart.clear()
        return render(request, 'order/checkoout_success.html', {'order': order})
    else:
        form = OrderCreateForm()
    return render(request, 'order/checkoout.html', {'form': form})


def payment_success(request):
    return render(request,'payment/success.html')


def payment_fail(request):
    return render(request,'payment/fail.html')




def orders(request):
    order_items = Order.objects.all()
    q = request.GET.get('q')
    if q:
        order_items = order_items.filter(Q(name__icontains=q)|Q(order_number__icontains=q))

    # print(order_items)
    context = {
        'order_items': order_items,
    }
    return render(request, 'order/order.html', context)


def order_items(request, order_number, pk):
    orders = get_object_or_404(Order, order_number=order_number, pk=pk)

    # order_item = orders.items.all()
    # for x in order_item:

    #     print(order_item)

    context = {
        'orders': orders,
        # 'order_items':order_items,
    }
    return render(request, 'order/orderitems.html', context)

templates/order/checkoout.html
{% extends 'header1.html' %}


{% load static %}
{% load humanize %}
{% load  crispy_forms_tags %}

<head>
    {% block head %}


    <title>

        {% block title %}
        Your Shopping Cart| Checkout
        {% endblock title %}
    </title>

    {% endblock head %}


</head>

{% block content %}

{% if messages %}

{% for message in messages %}
<div class="alert alert-{{message.tags}}" role="alert">
    {{message|safe}} <a href="/">Continue Shopping</a>
</div>

{% endfor %}

{% endif %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h4 class="page-headers">Checkout</h4>
            <form method="post">
                {% csrf_token %}
                {{  form|crispy}}<br>
                {% if cart.get_total_price < 1 %}
                <p class="text-danger  btn" style="color: #CE7F11;">your carrt is empty  </p>
                <a class="btn mx-6" style="background-color: #270949;color: white;" href="/">add some </a>
           
                {% else %}
                <input type="submit" class="btn btn-primary" value="Submit order" style="background-color: #4654A3;">

               
            </form>
            <div class="col-md-6">
                <div class="page-headers">
                    Your Order
                </div>
                <ul class="list-group">
                    {% for item in cart %}
                    <li class="list-group-item" >
                        {{ item.quantity }} {{ item.product.name }}
                        <span> Total GH₵: {{ item.total_price|intcomma }}</span>
                    </li>
                    {% endfor %}

                    <li class="list-group-item active" style="background-color: #FA7A62;">Total Cost: GH₵: {{ cart.get_total_price|intcomma }}</li>
                </ul>
            </div>
            {% endif %}
        </div>

        <div class="col-md-6">
            <div class="shiping-methods">
                <div class="section-title">
                    <h4 class="title">Shiping Methods</h4>
                </div>
                <div class="input-checkbox">
                    <input type="radio" name="shipping" id="shipping-1" checked>
                    <label for="shipping-1">Free Shiping - GH₵ 0.00</label>
                    <div class="caption">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                            incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                            nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                            <p>
                    </div>
                </div>
                <div class="input-checkbox">
                    <input type="radio" name="shipping" id="shipping-2">
                    <label for="shipping-2">Standard - GH₵ 4.00</label>
                    <div class="caption">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                            incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                            nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                            <p>
                    </div>
                </div>
            </div>

            <div class="payments-methods">
                <div class="section-title">
                    <h4 class="title">Payments Methods</h4>
                </div>
                <div class="input-checkbox">
                    <input type="radio" name="payments" id="payments-1" checked>
                    <label for="payments-1">Online payment</label>
                    <div class="caption">
                        
                        <!-- ipay -->
                            
                        <!-- ipay -->
                    </div>
                </div>
                <div class="input-checkbox">
                    <input type="radio" name="payments" id="payments-2">
                    <label for="payments-2">Pay On Delevery</label>
                    <div class="caption">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                            incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                            nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                            <p>
                    </div>
                </div>
                <div class="input-checkbox">
                    <input type="radio" name="payments" id="payments-3">
                    <label for="payments-3">Paypal System/(Pay In Foreign Currency)</label>
                    <div class="caption">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                            incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                            nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                            <p>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
{% if user.is_authenticated %}
    <script> 
    document.getElementById('id_name').value="{{request.user.get_full_name}}"
    document.getElementById('id_email').value="{{request.user.email}}"
    
    </script>
{% endif %}
{% endblock %}

templates/order/checkoout_success.html
{% extends 'header1.html' %}

{% load static %}

<head>

    {% block head %}

    <title>

        {% block title %}
        Your Shopping Cart| Thank you
        {% endblock %}
    </title>

    {% endblock head %}

</head>
{% block content %}
<div class="container">
    <div class="row justify-content-center" style="margin-top: 6%">
        <div class="col-md-8 col-md-offset-2">
            <h1 class="page-header">Thank You For Shopping With Us
            </h1>
            <h2>Your order has been successfully completed. Your order number is <strong class="text-info">{{ order.order_number }}</strong> you
                will be contacted soon <code>Thank you</code> </h2>
        </div>
    </div>
</div>
{% endblock %}

templates/order/order.html
{% extends 'header1.html' %}



{% load static %}

{% block content %}
<nav class="breadcrumb" style="margin-left:68%;font-size: larger;">

  <a style="background-color: #270949;color: white;" title="items bought"  data-toggle="tooltip" class="breadcrumb-item btn" href="{% url 'orders:orders' %}">Orders</a>

      <a style="background-color: #270949;color: white;" title="go home" data-toggle="tooltip" class="breadcrumb-item btn" href="/">Home</a>

</nav>
<div class="container">

    <h4 class="text-center display-4" style="font-weight: bolder;">ITEMS PURCHASED</h4>
    <div class="row">
        <div class="col">
            <section>
                <form action="#" method="GET">
                  <!-- <table class="table  table-sm"> -->
                  <table class="table table-bordered table-hover ">
                    <!-- search -->
                    <input class="my-3" type="text" name="q" id="" placeholder="search" value="{{ request.GET.q }}">
                    <button type="submit">search</button>
                    <hr>
                    <thead class="thead-light">
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Phone</th>
                        <th  scope="col">Email</th>
                        <th scope="col">Order Number</th>
                        <th scope="col">Paid</th>
                        <th scope="col">Date Issued</th>
                        <th scope="col">View</th>
                       
                      </tr>
                    </thead>
                    {% for orders in order_items %}
                    <tbody>
        
                      <tr style="font-size: x-large;">
                        <td id="id" scope="row"> {{forloop.counter}} </td>
                        <td scope="row"> {{ orders.name }} </td>
                        <td scope="row"> {{ orders.phone_number }} </td>
                        <td scope="row"> {{ orders.email }} </td>
                        <td scope="row"> {{ orders.order_number }} </td>
                        <td scope="row"> {{ orders.paid|yesno:'YES,NO' }} </td>

                        <td scope="row"> {{ orders.date_add }} </td>
                          <td scope="row"><a class="text-info btn" href="{% url 'orders:order_items' orders.order_number orders.pk %}">View</a></td>
                           
                      </tr>
                      {% empty %}
        
                      <p class="text-info"> Nothing to show currently</p>
                    </tbody>
        
                    {% endfor %}
                  </table>
                </form>
              </section>
        </div>
    </div>
</div>


{% endblock %}

templates/order/orderitems.html
{% extends 'header1.html' %}


{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static "css/tableexport.css" %}">
<script type="text/javascript" src="{% static 'jquery/jquery.min.js' %}"></script>
<script src="{% static "js/xlsx.min.js" %}"></script>

<script src="{% static "js/FileSaver.min.js" %}"></script>
<script src="{% static "js/tableexport.js" %}"></script>



<nav class="breadcrumb" style="margin-left:68%;font-size: larger;">

  <a style="background-color: #270949;color: white;" title="Items Bought" data-toggle='tooltip' class="breadcrumb-item btn" href="{% url 'orders:orders' %}">Items Bought</a>

      <a style="background-color: #270949;color: white;" title="" class="breadcrumb-item btn" href="/">Home</a>

</nav>
<div class="container">

    <div class="row">
        <div class="col">

      
       <h4 class="text-center display-4" style="font-weight: bolder;">ITEMS BY {{orders.name|upper}}</h4>

            <section>
                <form action="#" method="GET">
                  <!-- <table class="table  table-sm"> -->
                  <table class="table table-bordered table-hover">
                    <!-- search -->
                    <!-- <input class="my-3" type="text" name="q" id="" placeholder="search" value="{{ request.GET.q }}"> -->
                    <!-- <button type="submit">search</button> -->
                    <hr>
                    <ul style="list-style: square;font-weight: bolder;color: rgb(148, 121, 121);">
                        <li>Phone :{{orders.phone_number}}</li>
                        <li>Order Number: {{orders.order_number}}</li>
                        <li>Date Issued: {{orders.date_add}}</li>
                    </ul>
                    <thead class="thead-light active">
                      <tr style="font-size: x-large;">
                        <th scope="col">#</th>
                        <th scope="col">Category</th>
                        <th scope="col">Item</th>
                       <th scope="col">Quantity</th>
                       <th scope="col">Price</th>
                        <th>Totol</th>
                      </tr>
                    </thead>
                 
                    {% for  order in orders.items.all  %}
                      
                  
                    <tbody>
        
                      <tr style="font-size: x-large;">
                        <td id="id" scope="row"> {{forloop.counter}} </td>
                        <td scope="row"> {{ order.product.category }} </td>
                        <td scope="row"> {{ order.product.name }} </td>
                       
                       <td  scope="row">{{order.quantity}}</td>
                       <td  scope="row">{{order.product.price}}</td>
                       <td  scope="row">{{order.get_cost}}</td>

                      </tr>
        
                      {% empty %}
        
                      <p class="text-info"> Nothing to show currently</p>
                    </tbody>

                   <caption> {{order.grand_total}}</caption>
                    {% endfor %}
                  </table>
                </form>
              </section>
        </div>
    </div>
</div>


<script>



  $("table").tableExport({

// Displays table headers (th or td elements) in the <thead>
headers: true,                    

// Displays table footers (th or td elements) in the <tfoot>    
footers: true, 

// Filetype(s) for the export
formats: ["xls", "csv", "txt","xlsx"],           

// Filename for the downloaded file
fileName: "id",                         

// Style buttons using bootstrap framework  
bootstrap: false,

// Automatically generates the built-in export buttons for each of the specified formats   
exportButtons: true,                          

// Position of the caption element relative to table
position: "top",                   

// (Number, Number[]), Row indices to exclude from the exported file(s)
ignoreRows: null,                             

// (Number, Number[]), column indices to exclude from the exported file(s)              
ignoreCols: null,                   

// Removes all leading/trailing newlines, spaces, and tabs from cell text in the exported file(s)     
trimWhitespace: false,

// (Boolean), set direction of the worksheet to right-to-left (default: false)
RTL: false, 

// (id, String), sheet name for the exported spreadsheet, (default: 'id') 
sheetname: "id" 


});

</script>
{% endblock %}